import type { Metadata } from "next";
import { Geist, Geist_Mono,Heebo  } from "next/font/google";
import "./globals.css";


const heebo = Heebo({ subsets: ["hebrew"], weight: ["300", "400", "600", "700"] });



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="he" dir="rtl">
      <body className={heebo.className}>{children}</body>
    </html>
  );
}

